# Generated by Django 4.0.3 on 2022-04-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_user_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
