# Generated by Django 4.0.3 on 2022-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_rename_user_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='Ваш e-mail'),
        ),
    ]
