# Generated by Django 4.0.3 on 2022-04-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_usermodel_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_newsletter',
            field=models.BooleanField(verbose_name='Я соглашаюсь получать рассылку на почту'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_birthdate',
            field=models.DateField(verbose_name='Ваша дата рождения'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_gender',
            field=models.BooleanField(choices=[(1, 'Мужчина'), (2, 'Женщина'), (3, 'Другой')], verbose_name='Укажите свой пол'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(max_length=60, verbose_name='Введите пароль'),
        ),
    ]
