# Generated by Django 4.0.3 on 2022-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_usermodel_is_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_newsletter',
            field=models.BooleanField(default=False, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_gender',
            field=models.CharField(choices=[(1, 'Мужчина'), (2, 'Женщина'), (3, 'Другой')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(max_length=60, verbose_name='Пароль'),
        ),
    ]
